name: Test frontend

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/test-frontend.yml'

defaults:
  run:
    working-directory: 'frontend'
  
jobs:
  test_frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          package_json_file: 'frontend/package.json'
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: "frontend"
      - name: Install dependencies
        run: pnpm install
      - name: Run ESlint
        run: pnpm lint
      - name: Check formatting
        run: pnpm format:check
      - name: Build frontend
        run: pnpm build
